version: '3.8'

services:
  webpage_collect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:8080"
    environment:
      - WECHAT_APP_ID=
      - WECHAT_SECRET=
      - WECHAT_TOKEN=
      - WECHAT_ENCODING_AES_KEY=
      - FEISHU_APP_ID=
      - FEISHU_APP_SECRET=
      - OPENAI_API_BASE=
      - OPENAI_API_KEY
    restart: always
    volumes:
      - ./:/app
